conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 224,
	own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    double_buffer = true,
    minimum_width = 225,
    gap_x = 20,
	gap_y = 286,

    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    uppercase = true,
    border_inner_margin = 8,
}

conky.text = [[
BATTERIES  ${hr 2}
${font Oswald:size=8}Battery A: ${alignr}${if_existing /sys/class/power_supply/BAT0/status Charging}Charging${else}${if_existing /sys/class/power_supply/BAT0/status Discharging}Discharging${else}${if_existing /sys/class/power_supply/BAT0/status Not charging}Full${endif}${endif}${endif} ${battery_percent BAT0}%
${battery_bar 5 BAT0}
Battery B: ${alignr}${if_existing /sys/class/power_supply/BAT1/status Charging}Charging${else}${if_existing /sys/class/power_supply/BAT1/status Discharging}Discharging${else}${if_existing /sys/class/power_supply/BAT1/status Not charging}Full${endif}${endif}${endif} ${battery_percent BAT1}%
${battery_bar 5 BAT1}
]]

