conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 224,
	own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    double_buffer = true,
    minimum_width = 225,
    gap_x = 20,
	gap_y = 402,
    no_buffers = true,
    cpu_avg_samples = 1,
    uppercase = true,
    border_inner_margin = 8,
}


conky.text = [[
Network  ${hr 2}
${alignc}${font Oswald:size=8}${if_up usb0}USB${else}${if_existing /proc/net/route wlp3s0}${wireless_essid wlp3s0}${else}Not Connected${endif}${endif}
${if_existing /proc/net/route wlp3s0}${upspeedgraph wlp3s0 25,105}${alignr}${downspeedgraph wlp3s0 25,105}
UP ${upspeedf usb0} kib/s${alignr}Down ${downspeedf usb0} kib/s${endif}
]]

