conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 400,
	own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    double_buffer = true,
    minimum_width = 225,
    gap_x = 17,
	gap_y = 766,
    no_buffers = true,
    cpu_avg_samples = 1,
    uppercase = true,
    border_inner_margin = 10,
}

conky.text = [[
Processes ${hr 2}
${font Oswald:size=8}CPU ${alignr}$cpu%
${cpugraph cpu0 25,225}
Freq ${alignr}$freq_g Ghz
CPU Temp: ${alignr}${exec sensors | grep 'Package' | awk -F'+' '{print $2}' | awk -F'.' '{print $1}'}°C
Core 1: ${cpu cpu1}% ${alignr}${cpubar cpu1 6,140}
Core 2: ${cpu cpu3}% ${alignr}${cpubar cpu3 6,140}
Core 3: ${cpu cpu5}% ${alignr}${cpubar cpu5 6,140}
Core 4: ${cpu cpu7}% ${alignr}${cpubar cpu7 6,140}

Name: ${alignr} PID   CPU   MEM
${top name 1} $alignr ${top pid 1}  ${top cpu 1}  ${top mem 1}
${top name 2} $alignr ${top pid 2}  ${top cpu 2}  ${top mem 2}
${top name 3} $alignr ${top pid 3}  ${top cpu 3}  ${top mem 3}
${top name 4} $alignr ${top pid 4}  ${top cpu 4}  ${top mem 4}
${top name 5} $alignr ${top pid 5}  ${top cpu 5}  ${top mem 5}
]]
