conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 400,
	own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    double_buffer = true,
    minimum_width = 225,
    gap_x = 17,
	gap_y = 198,


    no_buffers = true,
    cpu_avg_samples = 1,
    uppercase = true,
    border_inner_margin = 10,
}

conky.text = [[
system  ${hr 2}
${font Oswald:size=8}Distro ${alignr}${exec lsb_release -ds}
Uptime: $alignr$uptime
]]