conky.config = {
    alignment = 'ml',
    background = false,
    border_width = 1,
	draw_borders = true,
	border_inner_margin = 15,
    color1 = '19A094',
    color2 = 'FF5252',
    cpu_avg_samples = 2,
	default_color = 'grey',
    default_outline_color = 'grey',
    default_shade_color = 'grey',
	double_buffer = true,    
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'Monaco:size=12',
    gap_x = 270,
    gap_y = 0,
    minimum_height = 5,
    maximum_width = 400,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_color = '19A094',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    stippled_borders = 0,
    update_interval = 1.2,
    uppercase = none,
    use_spacer = 'left',
    show_graph_scale = false,
    show_graph_range = false
}

conky.text = [[
NETWORKING$color${font} $hr 
${color2} External IP:$color ${exec curl -s www.icanhazip.com}
${if_up enx00e100004d8c}\
${color2}enx00e100004d8c\
 ${color}${font}${goto 270}${addrs enx00e100004d8c}
 ${color}Total:${totaldown enx00e100004d8c} \
 ${goto 210}${color}Total:${totalup enx00e100004d8c}
${downspeedgraph enx00e100004d8c 30,195 00ffff 19a094} \
${upspeedgraph enx00e100004d8c 30,195 00ffff 19A094}

${endif}\
${if_up wlp1s0}\
${color}${font}\
${color2}wlp1s0\
 ${color}${font}${goto 270}${addr wlp1s0}
 ${color white}${font}Strength:$color${wireless_link_qual_perc wlp1s0}%\
 ${goto 200}${color white}MAC: ${color}${wireless_ap wlp1s0}
 ${color}Total:${totaldown wlp1s0} \
 ${goto 210}${color}Total:${totalup wlp1s0}
${downspeedgraph wlp1s0 30,195 00ffff 19A094} \
${upspeedgraph wlp1s0 30,195 00ffff 19A094}

${endif}\
${if_up tun0}\
${color}${font}\
${color2}tun0\
 ${color}${font}${goto 270}${addr tun0}
 ${color}Total:${totaldown tun0} \
 ${goto 210}${color}Total:${totalup tun0}
${downspeedgraph tun0 30,195 00ffff 19A094} \
${upspeedgraph tun0 30,195 00ffff 19A094}
${endif}
${color1}${font Roboto Mono:style=Bold}\
]]