conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 1.0,
    uppercase = true,
    maximum_width = 270,
    minimum_width = 270,
    maximum_height = 0,
    minimum_height = 0,
    border_inner_margin = 8,
    own_window_argb_value = 205,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 170,
    gap_y = 60,
}
    
conky.text = [[
${font Oswald:size=14:bold}Battery  ${hr 3}
${font}External ${alignr}${if_existing /sys/class/power_supply/BAT0/status Charging}Charging${else}${if_existing /sys/class/power_supply/BAT0/status Discharging}Discharging${else}${if_existing /sys/class/power_supply/BAT0/status Not charging}${endif}${endif}${endif} ${battery_percent BAT0}%
${battery_bar 5 BAT0}
Internal ${alignr}${if_existing /sys/class/power_supply/BAT1/status Charging}Charging${else}${if_existing /sys/class/power_supply/BAT1/status Discharging}Discharging${else}${if_existing /sys/class/power_supply/BAT1/status Not charging}Full${endif}${endif}${endif} ${battery_percent BAT1}%
${battery_bar 5 BAT1}
]]
        