conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    minimum_width = 225,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    uppercase = true,
    border_inner_margin = 8,
    own_window_argb_value = 256,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 15,
    gap_y = 62,
}
    
conky.text = [[
TIME  ${hr 2}
${font Roboto:pixelsize=50}${alignr}${time %H:%M}${font}
${font Open Sans:pixelsize=11}${alignr}${time %Y-%m-%d}${font}
]];
        