conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 1.0,
    uppercase = true,
    maximum_width = 200,
    minimum_width = 200,
    maximum_height = 40,
    minimum_height = 40,
    border_inner_margin = 8,
    own_window_argb_value = 256,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 240,
    gap_y = 855,
}
    
conky.text = [[
darkmode
]];

        