conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 1.0,
    uppercase = true,
    maximum_width = 170,
    minimum_width = 170,
    maximum_height = 187,
    minimum_height = 187,
    border_inner_margin = 8,
    own_window_argb_value = 192,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 270,
    gap_y = 196,
}
    
        conky.text = [[
${font Oswald:size=14:bold}Memory  ${hr 3}
${font}${mem} / ${memmax}${alignr}${memperc}%
${membar 5}
Name${alignr}MEM
${top_mem name 1}${alignr}${top_mem mem 1}gib
${top_mem name 2}${alignr}${top_mem mem 2}gib
${top_mem name 3}${alignr}${top_mem mem 3}gib
${top_mem name 4}${alignr}${top_mem mem 4}gib
${top_mem name 5}${alignr}${top_mem mem 5}gib
]]
        