conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    minimum_width = 225,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    uppercase = true,
    border_inner_margin = 8,
    own_window_argb_value = 256,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 15,
    gap_y = 384,
}
    
        conky.text = [[
MEMORY  ${hr 2}
${font Oswald:size=8}${mem}/${memmax}${alignr}${memperc}%
${membar 5}

Name: ${alignr}MEM
${top_mem name 1}${alignr}${top_mem mem 1}gib
${top_mem name 2}${alignr}${top_mem mem 2}gib
${top_mem name 3}${alignr}${top_mem mem 3}gib
]]
        