conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 5.0,
    uppercase = true,
    maximum_width = 0,
    minimum_width = 0,
    maximum_height = 267,
    minimum_height = 267,
    border_inner_margin = 8,
    own_window_argb_value = 255,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 15,
    gap_y = 406,
}
    
conky.text = [[
${font Oswald:size=14:bold}${if_existing /sys/class/net/wlp3s0/operstate up}ONLINE${else}OFFLINE${endif}  ${hr 3}
${font Oswald:size=11:bold}PRIVATE${alignr}${addr wlp3s0}
PUBLIC${alignr}${exec curl -s www.icanhazip.com}
MAC${alignr}${wireless_ap wlp3s0}
${hr 3}
Down - ${downspeedf usb0} kib/s
${if_existing /proc/net/route wlp3s0}${downspeedgraph wlp3s0 25,160}
Up - ${upspeedf usb0} kib/s
${if_existing /proc/net/route wlp3s0}${upspeedgraph wlp3s0 25,160}]]
        