conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 1.0,
    uppercase = true,
    maximum_width = 239,
    minimum_width = 239,
    maximum_height = 100,
    minimum_height = 100,
    border_inner_margin = 8,
    own_window_argb_value = 191,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 201,
    gap_y = 406,
}
    
conky.text = [[
${font Oswald:size=14:bold}Processes  ${hr 3}
${font}Freq ${alignr}$freq_g Ghz
CPU Temp ${alignr}${exec sensors | grep 'Package' | awk -F'+' '{print $2}' | awk -F'.' '{print $1}'}°C
${cpugraph cpu0 25,236}
Core 1 ${alignr}${cpu cpu1}% ${cpubar cpu1 9,140}
Core 2 ${alignr}${cpu cpu3}% ${cpubar cpu3 9,140}
Core 3 ${alignr}${cpu cpu5}% ${cpubar cpu5 9,140}
Core 4 ${alignr}${cpu cpu7}% ${cpubar cpu7 9,140}
Name ${alignr} PID   CPU   MEM
${top name 1} $alignr ${top pid 1}  ${top cpu 1}
${top name 2} $alignr ${top pid 2}  ${top cpu 2}
${top name 3} $alignr ${top pid 3}  ${top cpu 3}
]]
        