conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 1.0,
    uppercase = true,
    maximum_width = 230,
    minimum_width = 230,
    maximum_height = 0,
    minimum_height = 0,
    border_inner_margin = 8,
    own_window_argb_value = 205,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 15,
    gap_y = 194,
}
    
conky.text = [[
${font Oswald:size=13:bold}SYSTEM  ${hr 3}${font}
${font Oswald:size=11:bold}Distro ${font Oswald:size=9:bold}${alignr}${exec lsb_release -ds}
${font Oswald:size=11:bold}Kernel ${font Oswald:size=9:bold}${alignr}${color}${kernel}
${font Oswald:size=11:bold}Uptime ${font Oswald:size=9:bold}${alignr}${uptime}
]]
        