conky.config = {
    alignment = 'top_left',
    font = 'Oswald:size=10:bold',
    use_xft = true,
    own_window = true,
    own_window_type = 'window',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    double_buffer = true,
    draw_shades = no,
    no_buffers = true,
    cpu_avg_samples = 1,
    update_interval = 1.0,
    uppercase = true,
    maximum_width = 425,
    minimum_width = 425,
    maximum_height = 120,
    minimum_height = 120,
    border_inner_margin = 8,
    own_window_argb_value = 192,
    own_window_colour = '#1C1C1E',
    default_color = '#FFFFFF',
    gap_x = 15,
    gap_y = 700,
}
    
conky.text = [[
${font Oswald:size=14:bold}Weather  ${hr 3}
${execi 100 scripts/weather.sh}\
${execi 100 scripts/weather-icon.sh $(jq -r '.weather[0].icon' scripts/weather.json)}\
${image scripts/weather-icon.png -p 240,-1 -s 175x175}\
${font Oswald:size=12:bold}${execi 100 jq -r '.name' scripts/weather.json} - ${execi 100 jq '.main.temp | floor' scripts/weather.json}°C
${execi 100 jq -r '.weather[0].description' scripts/weather.json | sed 's/.*/\u&/'}${font}
Wind: ${execi 100 jq '.wind.speed' scripts/weather.json} km/h
Humidity: ${execi 100 jq '.main.humidity' scripts/weather.json}%
Feels Like: ${execi 100 jq '.main.feels_like | floor' scripts/weather.json}°C
]];

        